directory = "_maps/map_files/tramstation/modular_pieces/"

[rooms.maintenance_upperdormsleft]
modules = ["maintenance_upperdormsleft_1.dmm", "maintenance_upperdormsleft_2.dmm"]

[rooms.maintenance_upperdormsleft_attachment]
modules = ["maintenance_upperdormsleft_attachment_1.dmm", "maintenance_upperdormsleft_attachment_2.dmm", "maintenance_upperdormsleft_attachment_3.dmm"]

[rooms.maintenance_upperdormsright]
modules = ["maintenance_upperdormsright_1.dmm", "maintenance_upperdormsright_2.dmm"]

[rooms.maintenance_upperdormsright_attachment]
modules = ["maintenance_upperdormsright_attachment_1.dmm", "maintenance_upperdormsright_attachment_2.dmm", "maintenance_upperdormsright_attachment_3.dmm"]

[rooms.maintenance_upperbridgeright]
modules = ["maintenance_upperbridgeright_1.dmm", "maintenance_upperbridgeright_2.dmm"]

[rooms.maintenance_upperbridgeright_attachment_a]
modules = ["maintenance_upperbridgeright_attachment_a_1.dmm", "maintenance_upperbridgeright_attachment_a_2.dmm", "maintenance_upperbridgeright_attachment_a_3.dmm"]

[rooms.maintenance_upperbridgeright_attachment_b]
modules = ["maintenance_upperbridgeright_attachment_b_1.dmm", "maintenance_upperbridgeright_attachment_b_2.dmm", "maintenance_upperbridgeright_attachment_b_3.dmm"]

[rooms.maintenance_upperbarright]
modules = ["maintenance_upperbarright_1.dmm", "maintenance_upperbarright_2.dmm"]

[rooms.maintenance_upperbarright_attachment_a]
modules = ["maintenance_upperbarright_attachment_a_1.dmm", "maintenance_upperbarright_attachment_a_2.dmm", "maintenance_upperbarright_attachment_a_3.dmm"]

[rooms.maintenance_upperbarright_attachment_b]
modules = ["maintenance_upperbarright_attachment_b_1.dmm", "maintenance_upperbarright_attachment_b_2.dmm", "maintenance_upperbarright_attachment_b_3.dmm"]

[rooms.maintenance_uppermedsci]
modules = ["maintenance_uppermedsci_1.dmm", "maintenance_uppermedsci_2.dmm"]

[rooms.maintenance_uppermedsci_attachment_a]
modules = ["maintenance_uppermedsci_attachment_a_1.dmm", "maintenance_uppermedsci_attachment_a_2.dmm", "maintenance_uppermedsci_attachment_a_3.dmm"]

[rooms.maintenance_uppermedsci_attachment_b]
modules = ["maintenance_uppermedsci_attachment_b_1.dmm", "maintenance_uppermedsci_attachment_b_2.dmm", "maintenance_uppermedsci_attachment_b_3.dmm"]

[rooms.maintenance_lowertunnel_leftup]
modules = ["maintenance_lowertunnel_leftup_1.dmm", "maintenance_lowertunnel_leftup_2.dmm"]

[rooms.maintenance_lowertunnel_leftup_attachment_a]
modules = ["maintenance_lowertunnel_leftup_attachment_a_1.dmm", "maintenance_lowertunnel_leftup_attachment_a_2.dmm", "maintenance_lowertunnel_leftup_attachment_a_3.dmm"]

[rooms.maintenance_lowertunnel_leftup_attachment_b]
modules = ["maintenance_lowertunnel_leftup_attachment_b_1.dmm", "maintenance_lowertunnel_leftup_attachment_b_2.dmm", "maintenance_lowertunnel_leftup_attachment_b_3.dmm"]

[rooms.maintenance_lowersecurity]
modules = ["maintenance_lowersecurity_1.dmm", "maintenance_lowersecurity_2.dmm"]

[rooms.maintenance_lowersecurity_attachment]
modules = ["maintenance_lowersecurity_attachment_1.dmm", "maintenance_lowersecurity_attachment_2.dmm", "maintenance_lowersecurity_attachment_3.dmm"]

[rooms.maintenance_lowerservicecargo]
modules = ["maintenance_lowerservicecargo_1.dmm", "maintenance_lowerservicecargo_2.dmm"]

[rooms.maintenance_lowerservicecargo_attachment_a]
modules = ["maintenance_lowerservicecargo_attachment_a_1.dmm", "maintenance_lowerservicecargo_attachment_a_2.dmm", "maintenance_lowerservicecargo_attachment_a_3.dmm"]

[rooms.maintenance_lowerservicecargo_attachment_b]
modules = ["maintenance_lowerservicecargo_attachment_b_1.dmm", "maintenance_lowerservicecargo_attachment_b_2.dmm"]

[rooms.maintenance_lowercargosci]
modules = ["maintenance_lowercargosci_1.dmm", "maintenance_lowercargosci_2.dmm"]

[rooms.maintenance_lowercargosci_attachment_a]
modules = ["maintenance_lowercargosci_attachment_a_1.dmm", "maintenance_lowercargosci_attachment_a_2.dmm", "maintenance_lowercargosci_attachment_a_3.dmm"]

[rooms.maintenance_lowercargosci_attachment_b]
modules = ["maintenance_lowercargosci_attachment_b_1.dmm", "maintenance_lowercargosci_attachment_b_2.dmm", "maintenance_lowercargosci_attachment_b_3.dmm"]

[rooms.maintenance_loweratmosci]
modules = ["maintenance_loweratmosci_1.dmm", "maintenance_loweratmosci_2.dmm"]

[rooms.maintenance_loweratmosci_attachment_a]
modules = ["maintenance_loweratmosci_attachment_a_1.dmm", "maintenance_loweratmosci_attachment_a_2.dmm", "maintenance_loweratmosci_attachment_a_3.dmm"]

[rooms.maintenance_loweratmosci_attachment_b]
modules = ["maintenance_loweratmosci_attachment_b_1.dmm", "maintenance_loweratmosci_attachment_b_2.dmm"]

[rooms.maintenance_lowerdormengie]
modules = ["maintenance_lowerdormengie_1.dmm", "maintenance_lowerdormengie_2.dmm"]

[rooms.maintenance_lowerdormengie_attachment_a]
modules = ["maintenance_lowerdormengie_attachment_a_1.dmm", "maintenance_lowerdormengie_attachment_a_2.dmm", "maintenance_lowerdormengie_attachment_a_3.dmm"]

[rooms.maintenance_lowerdormengie_attachment_b]
modules = ["maintenance_lowerdormengie_attachment_b_1.dmm", "maintenance_lowerdormengie_attachment_b_2.dmm", "maintenance_lowerdormengie_attachment_b_3.dmm"]

[rooms.maintenance_lowerdorm]
modules = ["maintenance_lowerdorm_1.dmm", "maintenance_lowerdorm_2.dmm"]

[rooms.maintenance_lowerdorm_attachment_a]
modules = ["maintenance_lowerdorm_attachment_a_1.dmm", "maintenance_lowerdorm_attachment_a_2.dmm", "maintenance_lowerdorm_attachment_a_3.dmm"]

[rooms.maintenance_lowerdorm_attachment_b]
modules = ["maintenance_lowerdorm_attachment_b_1.dmm", "maintenance_lowerdorm_attachment_b_2.dmm", "maintenance_lowerdorm_attachment_b_3.dmm"]
