name: Generate documentation
on:
  push:
    branches:
    - master
jobs:
  generate_documentation:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: sdmm_cache
        with:
          path: |
            ~/SpacemanDMM/target
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-SDMM-${{hashFiles('dependencies.sh')}}
      - name: Build SDMM
        if: steps.sdmm_cache.outputs.cache-hit != 'true'
        run: bash tools/ci/build_spaceman_dmm.sh
      - name: Generate documentation
        run: |
          cargo run --manifest-path ~/SpacemanDMM/Cargo.toml --release --bin dmdoc
          touch dmdoc/.nojekyll
          echo codedocs.tgstation13.org > dmdoc/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          FOLDER: dmdoc
